$(document).ready(function(){
	$("#follow").click(function(){
		$.ajax({
			url:"collection/collect.do",
			type:"post",
			dataType:"json",
			data:{
				colfo:$("#colfo").val()
			},
			success:function(data){
				alert(data.result);
				if(data.result==0){
					$("#colfollow").text("取消收藏");
					$("#colfo").val("1");
				}else{
					$("#colfollow").text("收藏");
					$("#colfo").val("0");
				}
			}
		});
	});
	$("#add").click(function(){
		$("#add").css("display","none");
		$("#tagInp").css("display","inline-block");
	});
	$("#tagInp").blur(function(){
		$.ajax({
			url:"collection/addcoltag.do",
			type:"post",
			dataType:"json",
			data:{
				tagname:$("#tagInp").val()
			},
			success:function(data){
				$("#add").css("display","block");
				$("#tagInp").css("display","none");
				location.reload();
			}
		});
	});
	$('.tag-single').hover(function(){
		$(this).find('button').css("display",'inline-block');
	},function(){
		$(this).find('button').css("display",'none');
	});
	$('.deltag').click(function(){
		$.ajax({
			url:'collection/delcoltag.do',
			type:"post",
			dataType:"json",
			data:{
				coltid:$(this).attr("p")
			},
			success:function(data){
				location.reload();
			}
		})
		
	});
});